### ISSUE TITLE
Best practice to pin `flake8`, a dependency of a dependency

### ISSUE THREAD

**Issue by valeriupredoi** [conda-forge/esmvalcore-feedstock#15]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

In light of this issue https://github.com/ESMValGroup/ESMValCore/issues/1405 that we solved in the package by adding the pinned `flake8<4` to the `test: ` section of dependencies in `setup.py` I am wondering what's the best way to pin `flake8` in our conda forge recipe: either adding it as requirement in `test: requires:` section of the recipe, or we should add a `run_constraint:` subsection in `test:` as instructed in https://conda-forge.org/docs/maintainer/adding_pkgs.html#constraining-packages-at-runtime since `flake8` is a dependency of a required dependency (`pytest-flake8`) but not an actual required dependency of our package :beer:

**Comment by zklaus** [comment]
I think the `test` section is only used during the build process to run the tests as, well, a test on whether the build was successful. As such it has no impact on the distributed builds and does not contain a `run_contrained`(sic) section.

`run_contrained` only applies to the overall requirements and can be used to declare limits on packages that can co-exist with our package, but are not installed as a dependency because they are not needed for its use.

In our case, flake is only needed for certain tests and the tests are not usually run by the user. As such, I think we should add flake with the necessary pinning to the `requires` subsection of the `test` section, but not to the requirements nor the `run_constrained` section of the main part.

**Comment by valeriupredoi** [comment]
cheers @zklaus - makes sense, shall we use this case to introduce Manuel/Axel/Remi to changing the conda forge recipe and rebuilding the package as a result when we talk to them on Feb 1st?

**Comment by schlunma** [comment]
This can be closed now.
